### PR TITLE
`cp --parents` does not work on macos by default

### PR DESCRIPTION
**Pull request by fivetentaylor**
Use `rsync -R` instead of `cp --parents`, since `--parents` is not an option on the built in `cp` of macOS. `rsync -R` seems pretty ubiquitous across all *nix

### CODE REVIEW

**Comment by mweidner037** [comment]
Thanks - looks like you just need to install rsync on readthedocs as well.
Should be possible in `readthedocs.yaml`: https://docs.readthedocs.io/en/stable/config-file/v2.html#build-apt-packages

**Comment by fivetentaylor** [comment]
Thanks @mweidner037! I added the readthedocs fix, but it looks like circleci is not reporting back status for me, it just hangs forever 🤔 Not sure if that means there is an error in circle ci I can't see, or maybe the yaml isn't parsing... or maybe it's fine and I just can't see.

**Comment by mweidner037** [comment]
Oh, I had to change a CircleCI setting.

Before merging this, I'll see if I can instead just remove the `cp --parents` commands. I recall they were for working around a weird TypeScript/JSDoc interaction that might have a better fix.

**Comment by mweidner037** [comment]
> Before merging this, I'll see if I can instead just remove the cp --parents commands. I recall they were for working around a weird TypeScript/JSDoc interaction that might have a better fix.

I did not figure out a workaround for this, so I'll use your rsync fix. Sorry for the delay in getting around to it.

**Pull request merged**
